name: CI Test Workflow

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y cmake g++ libgmp-dev

      - name: Set up Google Test
        run: |
          mkdir -p build
          cd build
          cmake -DGESTALT_BUILD_TESTS=ON -DGESTALT_FETCH_GOOGLETEST=ON ..
          make

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure
